# Generated by Django 6.0.7 on 2026-08-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='type',
            new_name='name',
        ),
    ]
